### ISSUE TITLE
nic się nie wyświetla Request not authenticated..

### ISSUE THREAD

**Issue by dzizes** [dzizes/staraio#102]
[W 160228 07:07:36 web:1521] 400 GET /api/courseseditions/ (::1): Request not authenticated..
[W 160228 07:07:36 web:1946] 400 GET /api/courseseditions/ (::1) 4.00ms
[W 160228 07:10:42 web:1521] 400 GET /api/grades/ (::1): Request not authenticated..
[W 160228 07:10:42 web:1946] 400 GET /api/grades/ (::1) 6.00ms
[W 160228 07:10:44 web:1521] 400 GET /api/terms/ (::1): Request not authenticated..
[W 160228 07:10:44 web:1946] 400 GET /api/terms/ (::1) 4.00ms
[W 160228 07:10:47 web:1521] 400 GET /api/programmes/ (::1): Request not authenticated..
[W 160228 07:10:47 web:1946] 400 GET /api/programmes/ (::1) 5.00ms
[W 160228 07:10:49 web:1521] 400 GET /api/lecturers/ (::1): Request not authenticated..
[W 160228 07:10:49 web:1946] 400 GET /api/lecturers/ (::1) 6.00ms

**Comment by smola222** [comment]
juz poprawione, scagnij
Wojciech Smołkowski
wojciech.smolkowski@gmail.com

**Comment by dzizes** [comment]
nie komituj czegoś co nie dziala, omawialiśmy to wielokrotnie
