### ISSUE TITLE
friends + friends suggestions

### ISSUE THREAD

**Issue by dzizes** [dzizes/staraio#12]
- wyświetlanie znajomych /friends/
- wyświetlanie propozycji znajomych /friends/suggestions
- dodanie znajomego z listy /friends/add
- usunięcie znajomego z listy /friends/remove

**Comment by smola222** [comment]
wszystko jest zrobione, tylko mam prosbe o sprawdzenie czy jest git. Jedyne co sie nie wyswietla to komunikaty, że dodano lub usnięto usera: 
            self.redirect("/friends/suggestions?added={0}".format(user_to_add_info_id))
            self.redirect("/friends?removed={0}".format(user_to_remove_info_id))
czy po stronie web'a w JS wystarczy ze zrobie if removed to komuniakt wyswietl? czy jest jakis pomysl na lepsze rozwiazanie?

**Comment by dzizes** [comment]
Tak parametrów nie zwracamy
Zrób tak jak robimy
URL ma być czysty

pon., 8 lut 2016, 00:42 smola222 użytkownik <notifications@github.com>
napisał:
