### ISSUE TITLE
Login/create user using FB account

### ISSUE THREAD

**Issue by smola222** [dzizes/staraio#29]
musi byc logowanie i tworzenie userwow przy pomocy FB i Google

tak jak np na http://crossweb.pl/rejestracja/, tylko 2 opcje do wyboru

**Comment by smola222** [comment]
jak mozesz zrob ty - zrobiles dla googla bedzie działo tez dla FB

**Comment by dzizes** [comment]
Ty możesz się nauczyć

pon., 8 lut 2016, 00:13 smola222 użytkownik <notifications@github.com>
napisał:
