### ISSUE TITLE
change back xsrf_cookies to True

### ISSUE THREAD

**Issue by dzizes** [dzizes/staraio#42]
xsrf_cookies=True,

**Comment by smola222** [comment]
wiem, ale potem jest problem z wywołaniem z JS posta... masz pomysł jak to zrobić?

**Comment by dzizes** [comment]
nie przepisuj do mnie

**Comment by smola222** [comment]
ok, ale nie wiem jak spytalem sie cyz ty nie wiesz moze jak to rozwiazac?

Wojciech Smołkowski
wojciech.smolkowski@gmail.com
