### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

### ISSUE THREAD

**Issue by smola222** [dzizes/staraio#86]
warning in js:

Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

have to change async to true, but after changes next problems..
async: false,

**Comment by smola222** [comment]
po zamknięciu

TypeError: Cannot read property 'USOS_API' of undefined(…)

**Comment by dzizes** [comment]
clean cache and start from main page /
