### ISSUE TITLE
SPA - fix layout in register to usos..

### ISSUE THREAD

**Issue by smola222** [dzizes/staraio#91]

**Comment by smola222** [comment]
nie wiem jak zrobić, żeby po zalogowaniu a bez saprowania się wyświeltała zawsze #register a po sparowaniu żeby się wyśieta już strona np. #main która bedzie stroną po zalogowaniu bo #home jest przed zalogowaniem..

**Comment by dzizes** [comment]
ja też nie wiem. pisałem wczoraj kilka godzin bo było do mnie przypisane i nadpisałeś wszystko

po zalogowaniu nie ma możliwości rejestracji

dodatkowo znowu nadpisałeś settings

**Comment by smola222** [comment]
trzeba w url wpisać #register

Wojciech Smołkowski
wojciech.smolkowski@gmail.com

**Comment by dzizes** [comment]
To nie jest rozwiazanie wcześniej działało
Przywróć poprawne działanie
